spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/users
    username: java
    password: java
    pool:
      enabled: true
  jpa:
    defer-datasource-initialization: true
feign:
  client:
    config:
      client:
        options:
          readTimeoutMillis: 2000
          writeTimeoutMillis: 2000
          responseTimeoutMillis: 2000